version: "3"
services:
  app:
    restart: always
    image: mydockerhub/kryptonite:latest
    build: . # Current directory!
    command: "gunicorn kryptonite.wsgi:application --bind 0.0.0.0:8000  --workers 2 --timeout 86400"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=name
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

