# Generated by Django 3.0.2 on 2020-01-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledDispatch',
            fields=[
                ('dispatchID', models.AutoField(primary_key=True, serialize=False)),
                ('dispatchRecipient', models.CharField(max_length=255)),
                ('dispatchItem', models.CharField(max_length=255)),
            ],
        ),
    ]
