# Generated by Django 3.0.2 on 2020-01-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleddispatch',
            name='dispatchRecipient',
            field=models.IntegerField(),
        ),
    ]
