# Generated by Django 3.0.2 on 2020-01-18 21:17

from django.db import migrations, models
import mails.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('accountID', models.AutoField(primary_key=True, serialize=False)),
                ('accountEmail', models.EmailField(max_length=254)),
                ('accountHolderName', models.CharField(max_length=255)),
                ('accountExpiryDate', models.DateTimeField(default=mails.models.get_default_my_date)),
            ],
        ),
        migrations.CreateModel(
            name='ExpiredAccounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accountEmail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
